CREATE TABLE FILES (
    FILE_ID NUMBER NOT NULL,
    FILE_NAME NVARCHAR2(50),
    FILE_FORMAT NVARCHAR2(3),
    FILE_SIZE NUMBER,
    STORAGE NUMBER,
    CONSTRAINT STORAGE_ID_FK FOREIGN KEY (STORAGE) REFERENCES STORAGE(ID)
);